<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DevSphere.Domain\DevSphere.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\" />
      <Folder Include="common\Behaviors\" />
      <Folder Include="common\Exceptions\" />
      <Folder Include="common\Interfaces\" />
      <Folder Include="common\Models\" />
      <Folder Include="Features\Coding Templates\" />
      <Folder Include="Features\LearningContents\" />
      <Folder Include="Features\MCQ Options\" />
      <Folder Include="Features\Questions\" />
      <Folder Include="Features\SubTopics\" />
      <Folder Include="Features\Technologies\Queries\GetTechnologyById\" />
      <Folder Include="Features\Test Cases\" />
      <Folder Include="Features\Topics\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="11.11.0" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
      <PackageReference Include="MediatR" Version="12.4.1" />
      <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    </ItemGroup>

</Project>
