<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DevSphere.Application\DevSphere.Application.csproj" />
      <ProjectReference Include="..\DevSphere.Domain\DevSphere.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="Dapper" Version="2.1.79" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.12" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.12" />
      <PackageReference Include="Npgsql" Version="9.0.3" />
      <PackageReference Include="RateLimiting" Version="1.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
